---
- name: Install HWCert repos
  yum_repository:
    name: hwcert
    description: hwcert YUM repo
    baseurl: http://{{ local_repo_ip }}/{{ topic }}/hwcert
    gpgcheck: false

- name: Copy files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: /opt/
  with_items:
    - hwcert-test-automation-dci-0.2-20200616.el7.noarch.rpm
    - pytest-4.6.11.tar.gz
    - pip-20.1.1-py2.py3-none-any.whl

- name: Install needed packages (RHEL-7)
  yum:
    name: ['redhat-certification-backend', 'redhat-certification-hardware', 'redhat-certification', '/opt/hwcert-test-automation-dci-0.2-20200616.el7.noarch.rpm']
    disable_gpg_check: true
  when: ansible_distribution_major_version == "7"

# NOTE: Provided test package does not work with RHEL-8 currently.
#       Execution of hwcert tests limited to RHEL-7 clients only in
#       main agent playbook.
- name: Install needed packages (RHEL-8)
  yum:
    name: ['redhat-certification-backend', 'redhat-certification-hardware', '/opt/hwcert-test-automation-dci-0.2-20200616.el7.noarch.rpm']
    disable_gpg_check: true
  when: ansible_distribution_major_version == "8"

- name: Extract pytest install artifacts
  unarchive:
    src: /opt/pytest-4.6.11.tar.gz
    dest: /opt
    remote_src: yes

- name: Install pytest
  shell: cd /opt; python pip-20.1.1-py2.py3-none-any.whl/pip install pytest --no-index --find-links ./

- name: Create directory for libvirt
  file:
    path: /etc/libvirt/qemu/
    recurse: true
    state: directory

- name: Create libvirt file to avoid download
  file:
    path: /etc/libvirt/qemu/hwcert-x86_64.xml
    state: touch

- name: Start rhcertd service
  service:
    name: rhcertd
    state: started

- name: Update rhcert.xml
  lineinfile:
    path: /etc/rhcert.xml
    regexp: '^  <urls.*>$'
    line: '  <urls phase="qa">'

- name: Restart rhcertd service
  service:
    name: rhcertd
    state: restarted

- name: Enable SELinux for HWCert tests
  selinux:
    policy: targeted
    state: enforcing

- name: Launch tests
  shell: hwcert-dci

- name: Put SELinux back in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Delete http conf file installed by cert
  file:
    path: /etc/httpd/conf.d/rhcert.conf
    state: absent

- name: Restart httpd service after deleting cert conf file
  service:
    name: httpd
    state: restarted

- name: Find files to upload
  find:
    paths: /tmp/hwcert_report
    patterns: '*'
  register: files_to_fetch

- name: Fetch files from tests
  fetch:
    src: "{{ item.path }}"
    dest: "{{ hostvars.localhost.job_logs.path }}/"
    flat: true
  with_items: "{{ files_to_fetch.files }}"
