---
- name: Install HWCert repos
  yum_repository:
    name: hwcert
    description: hwcert YUM repo
    baseurl: "{{ hwcert_url }}"
    gpgcheck: false

- name: Install extraOS
  yum_repository:
    name: extraOS
    description: extraos YUM repo
    baseurl: "{{ extraos_url }}"
    gpgcheck: false

- name: Install EPEL
  yum_repository:
    name: EPEL
    description: EPEL repo
    baseurl: '{{ epel_url }}'
    gpgcheck: false

- name: Copy files
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: /opt/
  with_items:
    - hwcert-sti
    - redhat-certification-hardware-spicegate-0.1-20181029.el7.noarch.rpm
    - yum-plugin-copr-1.1.31-45.el7.noarch.rpm
    - selenium-3.14.1.tar.gz

- name: Install needed packages
  yum:
    name: "{{ packages }}"
    disable_gpg_check: true
  vars:
    packages:
      - /opt/yum-plugin-copr-1.1.31-45.el7.noarch.rpm
      - /opt/redhat-certification-hardware-spicegate-0.1-20181029.el7.noarch.rpm
      - ansible
      - standard-test-roles
      - python2-behave
      - python-xvfbwrapper
      - python2-pyyaml
      - python-paramiko
      - python-six
      - unzip

- name: Extract Selenium
  unarchive:
    src: /opt/selenium-3.14.1.tar.gz
    dest: /opt/
    remote_src: true

- name: Install selenium
  command: python setup.py install
  args:
    chdir: /opt/selenium-3.14.1
    creates: /usr/lib/python2.7/site-packages/selenium-3.14.1-py2.7.egg

- name: Create directory for libvirt
  file:
    path: /etc/libvirt/qemu/
    recurse: true
    state: directory

- name: Create libvirt file to avoid download
  file:
    path: /etc/libvirt/qemu/hwcert-x86_64.xml
    state: touch

- name: Launch test
  command: ansible-playbook --tags classic tests.yml
  args:
    chdir: /opt/hwcert-sti
  changed_when: false
  ignore_errors: true

- name: Find files to upload
  find:
    paths: /tmp/artifacts
    patterns: '*'
  register: files_to_fetch

- name: Fetch files from tests
  fetch:
    src: "{{ item.path }}"
    dest: /tmp/joblogs-artifacts/
    flat: true
  with_items: "{{ files_to_fetch.files }}"
