---
- name: Install HWCert repos
  yum_repository:
    name: hwcert
    description: hwcert YUM repo
    baseurl: http://{{local_repo_ip}}/hwcert
    gpgcheck: no

- name: Install extraOS
  yum_repository:
    name: extraOS
    description: extraos YUM repo
    baseurl: http://{{local_repo_ip}}/extraos
    gpgcheck: no

- name: Install EPEL
  yum_repository:
      name: EPEL
      description: EPEL repo
      baseurl: '{{ epel_url }}'
      gpgcheck: no

- name: Copy HWcert
  copy:
    src: '{{ role_path }}/files/hwcert-sti'
    dest: /opt/

- name: Copy cert package
  copy:
    src: '{{ role_path }}/files/redhat-certification-hardware-spicegate-0.1-20181029.el7.noarch.rpm'
    dest: /opt/

- name: Copy copr package
  copy:
    src: '{{ role_path }}/files/yum-plugin-copr-1.1.31-45.el7.noarch.rpm'
    dest: /opt/

- name: Copy selenium tarball
  copy:
    src: '{{ role_path }}/files/selenium-3.14.1.tar.gz'
    dest: /opt/

- name: Copy importlib tarball
  copy:
    src: '{{ role_path }}/files/importlib-1.0.4.zip'
    dest: /opt/

- name: Install needed packages
  yum:
    name: "{{ packages }}"
    disable_gpg_check: yes
  vars:
    packages:
    - /opt/yum-plugin-copr-1.1.31-45.el7.noarch.rpm
    - /opt/redhat-certification-hardware-spicegate-0.1-20181029.el7.noarch.rpm
    - ansible
    - standard-test-roles
    - python2-behave
    - python-xvfbwrapper
    - python2-pyyaml
    - python-paramiko
    - python-six
    - unzip

- name: Extract Selenium
  unarchive:
    src: /opt/selenium-3.14.1.tar.gz
    dest: /opt/
    remote_src: yes

- name: Extract importlib
  unarchive:
    src: /opt/importlib-1.0.4.zip
    dest: /opt/
    remote_src: yes

- name: Install selenium
  command: python setup.py install
  args:
    chdir: /opt/selenium-3.14.1

- name: Install importlib
  command: python setup.py install
  args:
    chdir: /opt/importlib-1.0.4

- name: Create directory for libvirt
  file:
    path: /etc/libvirt/qemu/
    recurse: yes
    state: directory

- name: Create libvirt file to avoid download
  file:
    path: /etc/libvirt/qemu/hwcert-x86_64.xml
    state: touch

- name: Launch test
  command: ansible-playbook --tags classic tests.yml
  args:
    chdir: /opt/hwcert-sti
  ignore_errors: yes

- name: Find files to upload
  find:
    paths: /tmp/artifacts
    patterns: '*'
  register: files_to_fetch

- name: Fetch files from tests
  fetch:
    src: "{{ item.path }}"
    dest: /tmp/joblogs-artifacts/
    flat: yes
  with_items: "{{ files_to_fetch.files }}"
