---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint tasks
platforms:
  - name: el7
    image: centos:7
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_user: centos
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - create
    - prepare
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
